version: "3"
services:
  gotenberg:
    image: gotenberg/gotenberg:8
    restart: always
  pdftempl:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./pdfOut:/containerOut
    depends_on:
      gotenberg:
        condition: service_started
