apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg
  namespace: pdfgen
  labels:
    app: gotenberg-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gotenberg-app
  template:
    metadata:
      labels:
        app: gotenberg-app
    spec:
      containers:
        - name: gotenberg
          image: gotenberg/gotenberg:8
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            runAsUser: 1001
          ports:
          - name: gotenport
            containerPort: 3000
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.2"
            limits:
              memory: "1024Mi"
              cpu: "0.4"
