apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdfgen-app
  namespace: pdfgen
  labels:
    app: pdfgen-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdfgen-app
  template:
    metadata:
      labels:
        app: pdfgen-app
    spec:
      containers:
        - name: pdfgen-app
          image: tnaucoin/pdfgen
          imagePullPolicy: Never
          command: ["/bin/api"]
          ports:
          - name: httpport
            containerPort: 8000
          envFrom:
            - configMapRef:
                name: pdfgen-app-config
          volumeMounts:
            - mountPath: "/var/containerOut"
              name: pdf-vol
          readinessProbe:
            httpGet:
              port: 8000
              path: /livez
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 8000
              path: /livez
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
      volumes:
        - name: pdf-vol
          persistentVolumeClaim:
            claimName: pdf-pvc

