apiVersion: v1
kind: Service
metadata:
  name: pdfgen-app
  namespace: pdfgen
  labels:
    app: pdfgen-app
spec:
    selector:
        app: pdfgen-app
    ports:
    - name: httpport
      protocol: TCP
      port: 8000
      targetPort: 8000
    type: NodePort